/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef SXS_META_INTERFACE_PROTOCOL_H
#define SXS_META_INTERFACE_PROTOCOL_H

/* Host-visible vendor commands owned by the built-in meta-interface policy. */
#define SXS_NVME_ADMIN_INIT_SESSION_SUBMIT 0x93U
#define SXS_NVME_ADMIN_INIT_SESSION_FETCH 0x94U
#define SXS_NVME_ADMIN_INSTALL_POLICY 0x95U
#define SXS_NVME_ADMIN_DEACTIVATE_POLICY 0x97U
#define SXS_NVME_ADMIN_REMOVE_POLICY 0x99U
#define SXS_NVME_ADMIN_ATTESTATION_FETCH 0x9aU
#define SXS_NVME_ADMIN_ACTIVATE_POLICY 0x9bU
#define SXS_NVME_ADMIN_UPDATE_POLICY 0x9dU
#define SXS_NVME_ADMIN_ATTESTATION_SUBMIT 0x9fU

#define SXS_SESSION_MODE_NORMAL 0U
#define SXS_SESSION_MODE_CONFIDENTIAL 1U

#define SXS_INIT_SESSION_REQUEST_SIZE 105U
#define SXS_INIT_SESSION_RESPONSE_SIZE 104U

#define SXS_META_INTERFACE_POLICY_ID 0xffff0001U
#define SXS_META_INTERFACE_POLICY_VERSION 1U

/*
 * Attestation request (19 bytes): version:u8, report_type:u8,
 * history_mode:u8, nonce[16]. A delta request appends base_sequence:u64.
 *
 * Response header (76 bytes): version:u8, report_type:u8, history_mode:u8,
 * policy_count:u8, snapshot_sequence:u64, boot_epoch[16], nonce[16], and
 * history_head[32]. Policy entries and history records follow. The final 64
 * bytes are an Ed25519 signature over every preceding response byte.
 */
#define POLICY_ATTESTATION_FORMAT_VERSION 1

#define POLICY_ATTESTATION_REPORT_SECURITY 1
#define POLICY_ATTESTATION_REPORT_CONSISTENCY 2

#define POLICY_ATTESTATION_HISTORY_CHECKPOINT 1
#define POLICY_ATTESTATION_HISTORY_DELTA 2
#define POLICY_ATTESTATION_HISTORY_FULL 3

#define POLICY_HISTORY_OP_INSTALL 1
#define POLICY_HISTORY_OP_UPDATE 2
#define POLICY_HISTORY_OP_ACTIVATE 3
#define POLICY_HISTORY_OP_DEACTIVATE 4
#define POLICY_HISTORY_OP_REMOVE 5

#define POLICY_ATTESTATION_NONCE_SIZE 16
#define POLICY_ATTESTATION_BOOT_EPOCH_SIZE 16
#define POLICY_ATTESTATION_HASH_SIZE 32
#define POLICY_ATTESTATION_SIGNATURE_SIZE 64
#define POLICY_ATTESTATION_REQUEST_SIZE 19
#define POLICY_ATTESTATION_DELTA_REQUEST_SIZE 27
#define POLICY_ATTESTATION_RESPONSE_HEADER_SIZE 76
#define POLICY_ATTESTATION_SECURITY_ENTRY_SIZE 9
#define POLICY_ATTESTATION_CONSISTENCY_ENTRY_SIZE 41
#define POLICY_ATTESTATION_HISTORY_RECORD_SIZE 9
#define POLICY_ATTESTATION_MAX_POLICIES 16

#endif /* SXS_META_INTERFACE_PROTOCOL_H */
