#ifndef POLICY_ENGINE_TYPES_H
#define POLICY_ENGINE_TYPES_H

#define MAX_BACKEND_EVENT_HOOKS (256)
#define MAX_PSWD_TRANSITION_HOOKS (64)
#define MAX_BACKGROUND_HOOKS (64)
#define MAX_ADMIN_HOOKS (256)

#endif /* POLICY_ENGINE_TYPES_H */
